[workspace]
   members = [
      "examples/2d/shapes_2d",
      "examples/2d/viewport_to_world_2d",
      "examples/2d/bloom_2d",
      "hello_world"
]

[profile.release]
opt-level = 3

[workspace.dependencies]
bevy = { version = "0.15", features = ["default"] }
